### ISSUE TITLE
more classifier

### ISSUE THREAD

**Issue by Jaylton** [sherrardTr4129/Haar_Cascade_Classifiers#1]
you have more classifiers?

**Comment by sherrardTr4129** [comment]
Hello!

What I have in that repository is up to date. I am planning to begin
training more soon. I usually train several over the course of a few days
and then take a break from it for a while. I will say that I have written a
tutorial on how to train your own classifiers if you are interested in
doing so for yourself. It can be found on my personal website
http://trevorsherrard.com/Haar_training.html. I personally believe it is
a good resource, but there are others on the subject as well obviously.

Let me know if there is anything else I can do to help, and good luck!
-Trevor Sherrard

**Comment by Jaylton** [comment]
thanks, in Training the Cascade Classifier: shows this error:
  opencv_traincascade: command not found
because? and how to fix?

**Comment by sherrardTr4129** [comment]
That sounds like you don't have the traincascade utility working correctly.

**Comment by sherrardTr4129** [comment]
Closing issue for now. I will make sure to put up more classifiers soon as I train more. If you need help configuring or installing OpenCV please see the questions [page](http://answers.opencv.org/questions/).
