### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Determine06** [sherrardTr4129/Haar_Cascade_Classifiers#2]
I have a question?

How did make the Haar-Cascade-Classifiers

**Comment by sherrardTr4129** [comment]
Hey there!

I wrote a tutorial outlining the process that I used to create the Haar Cascade Classifiers you see in this repository. That tutorial can be found here: http://www.trevorsherrard.com/html/Haar_training.html

Please note that this tutorial was written assuming you are using opencv-2.4.5. So you may need to tweak some things as I assume you are using a newer version of OpenCV at this point.
